import { all_routes } from "../../feature-module/router/all_routes";

const routes = all_routes;


  export const  header = [
      {
        title: 'Home',
        showAsTab: false,
        separateRoute: true,
        hasSubRoute: false,
        showSubRoute: false,
        routes: routes.home,
        megaMenu: false,
        base: 'home'
      },
      {
        tittle: 'Gigs',
        showAsTab: false,
        separateRoute: false,
        base: 'gigs',
        menu: [
          {
            menuValue: 'Gigs Grid',
            routes: routes.service,
            hasSubRoute: false,
            showSubRoute: false,
            base: 'gigs',
            page: 'service',
            page2: '',
            page3: '',
            page4: '',
            page5: '',
            page6: '',
            subMenus: [],
          },
          {
            menuValue: 'Gig Left Sidebar',
            routes: routes.serviceGridSidebar,
            hasSubRoute: false,
            showSubRoute: false,
            base: 'gigs',
            page: 'service-grid-sidebar',
            page2: '',
            page3: '',
            page4: '',
            page5: '',
            page6: '',
            subMenus: [],
          },
          {
            menuValue: 'Gig Details',
            routes: routes.serviceDetails,
            hasSubRoute: false,
            showSubRoute: false,
            base: 'gigs',
            page: 'service-details',
            page2: '',
            page3: '',
            page4: '',
            page5: '',
            page6: '',
            subMenus: [],
          },
          {
            menuValue: 'Gig Category',
            routes: routes.categories,
            hasSubRoute: false,
            showSubRoute: false,
            base: 'gigs',
            page: 'categories',
            page2: '',
            page3: '',
            page4: '',
            page5: '',
            page6: '',
            subMenus: [],
          },
          {
            menuValue: 'Gig Category 2',
            routes: routes.categories2,
            hasSubRoute: false,
            showSubRoute: false,
            base: 'gigs',
            page: 'categories-2',
            page2: '',
            page3: '',
            page4: '',
            page5: '',
            page6: '',
            subMenus: [],
          },
          {
            menuValue: 'Gig Subcategory',
            routes: routes.serviceSubCategory,
            hasSubRoute: false,
            showSubRoute: false,
            base: 'gigs',
            page: 'service-sub-category',
            page2: '',
            page3: '',
            page4: '',
            page5: '',
            page6: '',
            subMenus: [],
          },
          {
            menuValue: 'Create a Gig',
            routes: routes.addGigs,
            hasSubRoute: false,
            showSubRoute: false,
            base: 'gigs',
            page: 'add-gigs',
            page2: '',
            page3: '',
            page4: '',
            page5: '',
            page6: '',
            subMenus: [],
          },
        ],
      },
      {
        tittle: 'Pages',
        showAsTab: false,
        separateRoute: false,
        base: 'pages',
        menu: [
          {
            menuValue: 'About Us',
            routes: routes.aboutUs,
            hasSubRoute: false,
            showSubRoute: false,
            base: 'pages',
            page: 'about-us',
            page2: '',
            page3: '',
            page4: '',
            page5: '',
            page6: '',
            subMenus: [],
          },
          // {
          //   menuValue: 'Our Team',
          //   hasSubRoute: true,
          //   showSubRoute: false,
          //   base: 'pages',
          //   page: 'our-team',
          //   subMenus: [
          //     {
          //       menuValue: 'Team Grid',
          //       // routes: routes.team,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'pages',
          //       page: 'our-team',
          //       last: 'team',
          //       subMenus: [],
          //     },
          //     {
          //       menuValue: 'Team Carousel',
          //       // routes: routes.teamCarousel,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'pages',
          //       page: 'our-team',
          //       last: 'team-carousel',
          //       subMenus: [],
          //     },
          //     {
          //       menuValue: 'Team Details',
          //       // routes: routes.teamDetails,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'pages',
          //       page: 'our-team',
          //       last: 'team-details',
          //       subMenus: [],
          //     },
          //   ],
          // },
          // {
          //   menuValue: 'Authentication',
          //   hasSubRoute: true,
          //   showSubRoute: false,
          //   base: 'pages',
          //   page: 'authentication',
          //   subMenus: [
          //     {
          //       menuValue: 'Login',
          //       // routes: routes.signIn,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'signin',
          //       last: '',
          //       subMenus: [],
          //     },
          //     {
          //       menuValue: 'Register',
          //       // routes: routes.signUp,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'signup',
          //       last: '',
          //       subMenus: [],
          //     },
          //     {
          //       menuValue: 'Forgot Password',
          //       // routes: routes.forgotPassword,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'forgot-password',
          //       last: '',
          //       subMenus: [],
          //     },
          //     {
          //       menuValue: 'Lock Screen',
          //       // routes: routes.lockScreen,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'lock-screen',
          //       last: '',
          //       subMenus: [],
          //     },
          //   ],
          // },
          // {
          //   menuValue: 'Error Pages',
          //   hasSubRoute: true,
          //   showSubRoute: false,
          //   base: 'pages',
          //   page: 'error-pages',
          //   subMenus: [
          //     {
          //       menuValue: 'Error 404',
          //       routes: routes.error404,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'error-404',
          //       last: '',
          //       subMenus: [],
          //     },
          //     {
          //       menuValue: 'Error 500',
          //       // routes: routes.error500,
          //       hasSubRoute: false,
          //       showSubRoute: false,
          //       base: 'error-500',
          //       last: '',
          //       subMenus: [],
          //     },
          //   ],
          // },
          // {
          //   menuValue: 'Portfolio',
          //   // routes: routes.portfolio,
          //   hasSubRoute: false,
          //   showSubRoute: false,
          //   page: 'portfolio',
          //   page2: 'portfolio-details',
          //   page3: '',
          //   page4: '',
          //   page5: '',
          //   page6: '',
          //   subMenus: [],
          // },
          // {
          //   menuValue: 'Pricing',
          //   // routes: routes.pricing,
          //   hasSubRoute: false,
          //   showSubRoute: false,
          //   base: 'pages',
          //   page: 'pricing',
          //   page2: '',
          //   page3: '',
          //   page4: '',
          //   page5: '',
          //   page6: '',
          //   subMenus: [],
          // },
          // {
          //   menuValue: 'Maintenance',
          //   // routes: routes.underConstruction,
          //   hasSubRoute: false,
          //   showSubRoute: false,
          //   base: 'pages',
          //   page: 'under-construction',
          //   page2: '',
          //   page3: '',
          //   page4: '',
          //   page5: '',
          //   page6: '',
          //   subMenus: [],
          // },
          // {
          //   menuValue: 'Coming Soon',
          //   // routes: routes.comingSoon,
          //   hasSubRoute: false,
          //   showSubRoute: false,
          //   base: 'pages',
          //   page: 'coming-soon',
          //   page2: '',
          //   page3: '',
          //   page4: '',
          //   page5: '',
          //   page6: '',
          //   subMenus: [],
          // },
        ],
      },
      
    ];
  