export const userPayments = [
  {
    id: "#157",
    key:1,
    reason: "I will do designing and executing...",
    buyer: "Jones",
    dateTime: "22 May 2023 10:50PM",
    type: "Cancelled",
    amount2: "$1454",
    img: "assets/img/gigs/gigs-09.jpg",
    img2: "assets/img/user/user-01.jpg",
  },
  {
    id: "#156",
    key:2,
    reason: "I will develop openai, dalle, chat...",
    buyer: "Adrian",
    dateTime: "21 May 2023 11:25 PM",
    type: "Recieved",
    amount2: "$1154",
    img: "assets/img/gigs/gigs-03.jpg",
    img2: "assets/img/user/user-02.jpg",
  },
  {
    id: "#155",
    key:3,
    reason: "I will do professional lifestyle and...",
    buyer: "Andrea",
    dateTime: "17 May 2023 12:16 AM",
    type: "Recieved",
    amount2: "$6547",
    img: "assets/img/gigs/gigs-02.jpg",
    img2: "assets/img/user/user-03.jpg",
  },
  {
    id: "#154",
    key:4,
    reason: "Embedded Android & AOSP...",
    buyer: "Martin",
    dateTime: "15 May 2023 11:21 PM",
    type: "Recieved",
    amount2: "$1454",
    img: "assets/img/gigs/gigs-04.jpg",
    img2: "assets/img/user/user-04.jpg",
  },
  {
    id: "#153",
    key:5,
    reason: "I will do creating and promoting...",
    buyer: "James",
    dateTime: "10 May 2023 09:20PM",
    type: "Recieved",
    amount2: "$1454",
    img: "assets/img/gigs/gigs-13.jpg",
    img2: "assets/img/user/user-05.jpg",
  },
];
