export const userFilesData = [
  {
    ids: "#120",
    key:1,
    uploadedFor: "I will do designing and executing targeted email campaigns",
    uploadedOn: "22 May 2023",
    uploadedBy: "Jones",
    fileType: "Jpg",
    img1: "assets/img/gigs/gigs-09.jpg",
    img2: "assets/img/user/user-01.jpg",
  },
  {
    ids: "#119",
    key:2,
    uploadedFor: "I will develop openai, dalle, chat gpt app for mobile",
    uploadedOn: "20 May 2023",
    uploadedBy: "Adrian",
    fileType: "Mp4",
    img1: "assets/img/gigs/gigs-03.jpg",
    img2: "assets/img/user/user-02.jpg",
  },
  {
    ids: "#118",
    key:3,
    uploadedFor: "I will do professional lifestyle and product photography",
    uploadedOn: "15 May 2023",
    uploadedBy: "Andrea",
    fileType: "Png",
    img1: "assets/img/gigs/gigs-02.jpg",
    img2: "assets/img/user/user-03.jpg",
  },
  {
    ids: "#117",
    key:4,
    uploadedFor: "Embedded Android & AOSP customizations",
    uploadedOn: "27 Apr 2023",
    uploadedBy: "Martin",
    fileType: "Png",
    img1: "assets/img/gigs/gigs-04.jpg",
    img2: "assets/img/user/user-04.jpg",
  },
  {
    ids: "#116",
    key:5,
    uploadedFor:
      "I will do creating and promoting video content to engage audiences",
    uploadedOn: "19 Apr 2023",
    uploadedBy: "James",
    fileType: "Png",
    img1: "assets/img/gigs/gigs-13.jpg",
    img2: "assets/img/user/user-05.jpg",
  },
  {
    ids: "#115",
    key:6,
    uploadedFor:
      "I will do implementing chatbots on websites or messaging apps",
    uploadedOn: "03 Apr 2023",
    uploadedBy: "Hendy",
    fileType: "Mp4",
    img1: "assets/img/gigs/gigs-05.jpg",
    img2: "assets/img/user/user-06.jpg",
  },
  {
    ids: "#120",
    key:7,
    uploadedFor: "I will develop openai, dalle, chat gpt app for mobile",
    uploadedOn: "20 May 2023",
    uploadedBy: "Adrian",
    fileType: "Mp4",
    img1: "assets/img/gigs/gigs-03.jpg",
    img2: "assets/img/user/user-07.jpg",
  },
  {
    ids: "#121",
    key:8,
    uploadedFor: "I will do professional lifestyle and product photography",
    uploadedOn: "15 May 2023",
    uploadedBy: "Andrea",
    fileType: "Png",
    img1: "assets/img/gigs/gigs-02.jpg",
    img2: "assets/img/user/user-08.jpg",
  },
  {
    ids: "#122",
    key:9,
    uploadedFor: "Embedded Android & AOSP customizations",
    uploadedOn: "27 Apr 2023",
    uploadedBy: "Martin",
    fileType: "Png",
    img1: "assets/img/gigs/gigs-04.jpg",
    img2: "assets/img/user/user-09.jpg",
  },
  {
    ids: "#123",
    key:10,
    uploadedFor:
      "I will do creating and promoting video content to engage audiences",
    uploadedOn: "19 Apr 2023",
    uploadedBy: "James",
    fileType: "Png",
    img1: "assets/img/gigs/gigs-13.jpg",
    img2: "assets/img/user/user-10.jpg",
  },
  {
    ids: "#124",
    key:11,
    uploadedFor:
      "I will do implementing chatbots on websites or messaging apps",
    uploadedOn: "03 Apr 2023",
    uploadedBy: "Hendy",
    fileType: "Mp4",
    img1: "assets/img/gigs/gigs-05.jpg",
    img2: "assets/img/user/user-11.jpg",
  },
];
